apiVersion : apps/v1
kind : Deployment
metadata :
  name : nginx-deployment
spec :
  replicas : 1
  selector :
    matchLabels :
      app : nginx
  template :
    metadata :
      labels :
        app : nginx 
    spec :
      containers :
      - name : nginx
        image : 577811233724.dkr.ecr.us-east-1.amazonaws.com/nginx
        ports :
        - containerPort : 80
      resources :
        limits :
          memory : "128Mi"
          cpu : "500m"
        requests :
          memory : "64Mi"
          cpu : "250m"  
      livenessProbe :
        httpGet :
          path : /
          port : 80
        initialDelaySeconds : 30
        periodSeconds : 10
      redinessProbe :
        httpGet :
          path : /
          port : 80
        initialDelaySeconds : 30
        periodSeconds : 10    

      volumes : 
      - name : nginx-pvc
        persistentVolumeClaim :
          claimName : nginx-pvc  